# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
      target: final
    volumes:
      - ./log:/bin/logFile
    container_name: easyChatServer
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: easyChatDB
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: easyChatRedis
    healthcheck:
      test: ["CMD", "redis-cli", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  kafka:
    image: apache/kafka:latest
    restart: unless-stopped
    container_name: easyChatKafka
    healthcheck:
      test: ["CMD", "kafka-server-status.sh", "localhost:9092"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: PLAINTEXT://localhost:${KAFKA_PORT},CONTROLLER://localhost:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:${KAFKA_PORT}
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_NUM_PARTITIONS: 3
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
volumes:
    mysql_data:
# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
  # db:
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   container_name: easyChatDB
  #   environment:
  #     MYSQL_ROOT_PASSWORD: your_password
  #     MYSQL_DATABASE: chat
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - mysql-data:/var/lib/mysql    # 数据持久化
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 初始化脚本（可选）
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  

